[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "uuid", "chrono", "macros"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }
chrono = { workspace = true }